outDir: out

manifest:
  main: package.nw/app/nw/index.js
  chromium-args: --mixed-context --disable-web-security
  domain: lenz
  window:
    icon: icon.png

app:
  id: lenz
  name: Lenz Editor
  version: 0.0.1
  description: A simple editor.
  author: Salomão Neto <contato@sallon.dev>

nw:
  version: 0.86.0
  arch: x64
  flavor: normal

hooks:
  pre-build:
    - "pnpm build:core"
    - "pnpm build:app"

platforms:
  linux:
    arch:
      - amd64
    launchers:
      - name: Lenz Editor
        exec: lenz
        icon: lenz
        categories:
          - Development
    bin:
      lenz: "/usr/share/lenz/nw"

    target:
      plain:
      deb:
        # build:
        #   compression: none
        #   compressionLevel: 0
        #   compressionStrategy: none
      appImage:
        run: ./usr/share/lenz/nw
        icon: icon.png

sources:
  - from: packages/app
    to: .
    filter:
      - "splash.html"
      - "icon.png"

  - from: packages
    to: package.nw
    filter:
      - "app/package.json"
      - "app/dist/**"
      - "app/nw/**"

  - from: packages/extensions
    to: package.nw/extensions

  - from: packages/app/node_modules/lenz
    to: node_modules/lenz
    filter:
      - package.json
      - dist/**
      - "!**/*.d.ts"
